version: '3.7'

services:
  frontend:
    container_name: frontend
    build: ./frontend
    environment:
      - NODE_SERVER=http://localhost:5000
      - RESOURCE_SERVER_PLAYERS_ENDPOINT=http://resource-server:8080/favouritePlayers
      - CLIENT_ID=devflection-node-js
      - CLIENT_SECRET=iLnAxjsRGIHtE7HcoTwAH7wap1EIrrM9
      - SCOPE=devflectionPlayers
      - TOKEN_ENDPOINT_URL=http://keycloak:8080/auth/realms/master/protocol/openid-connect/token
      - AUTHORIZE_REQUEST_URL=http://localhost:8083/auth/realms/master/protocol/openid-connect/auth
      - REDIRECT_URI=http://localhost:5000/authorizationCallback      
    ports:
      - 5000:5000
  resource-server:
    container_name: resource-server
    build: ./resource-server
    environment:
      - OAUTH_ISSUER_URI=http://keycloak:8080/auth/realms/master
      - PORT=8080
    ports:
      - 8080:8080
  keycloak:
      image: quay.io/keycloak/keycloak:legacy
      environment:       
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
        KEYCLOAK_FRONTEND_URL: http://keycloak:8080
      ports:
        - 8083:8080